### ISSUE TITLE
lua-sql FTBFS with MariaDB 10.3 (Debian)

### ISSUE THREAD

**Issue by fauust** [keplerproject/luasql#108]
Hi,
I am filling this issue, to link it to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918387 and to be sure that upstream dev are aware of it.

As explained by Sergei (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919395#36)
> error: 'MYSQL_SERVER_VERSION' undeclared
> 
>   this looks like a bug. MYSQL_SERVER_VERSION is documented here:
>   https://dev.mysql.com/doc/refman/5.5/en/c-api-server-client-versions.html

Regards,
Faustin

**Comment by anbe42** [comment]
This was fixed in mariadb-10.3 1:10.3.13-1, no action is needed on the lua-sql side.
