### ISSUE TITLE
luasql 5.2

### ISSUE THREAD

**Issue by mrjoli021** [keplerproject/luasql#14]
Hello,

We have installed the latest version of Freeswitch and we are attempting to install luasql to use it on one of our scripts.  We have installed it as per the instructions, but for some reason it puts it as lua5.1.  when we run it through Freeswitch, Freeswitch is asking for 5.2.  We created a simlink and below is the error we get.  Is there a way to force luasql with 5.2 .  According to the instruction it should be compatible.

2013-12-30 07:33:30.352599 [ERR] mod_lua.cpp:199 error loading module 'luasql.mysql' from file '/usr/local/lib/lua/5.2/luasql/mysql.so': 
	        /usr/local/lib/lua/5.2/luasql/mysql.so: undefined symbol: lua_getfield                                                             
	stack traceback:                                                                                                                         
	        [C]: in ?                                                                                                                          
	        [C]: in function 'require'                                                                                                         
	        /usr/local/freeswitch/scripts/callerID.lua:6: in main chunk

Thanks,

**Comment by tomasguisasola** [comment]
Although I am too late to say that, LuaSQL already support Lua 5.2.
