### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by grasses** [keplerproject/luasql#33]
how to install in mac.
my lua path is: /usr/local/lib/lua

**Comment by tomasguisasola** [comment]
Hi

I need more information to help you.

To install LuaSQL you need to choose a database driver according to your 
database (you will also need a developer's package for that database, to 
provide the header files necessary to compile C code).  You can install 
it manually, using the Makefile provided by the package, or you can 
install it using LuaRocks.  Lua version (and the header files) is (are) 
also a necessary information.

Regards,
Tomás

**Comment by grasses** [comment]
My Lua version is Lua 5.2.3, I want to install luasql.mysql.
I do not know how to install manually using the Makefile in Mac.
then I try it by luarocks.

I use command:
luarocks install luasql-mysql MYSQL_DIR=/usr/local/Cellar/mysql/5.6.23/include/mysql

It tells me:
Could not find expected file mysql.h, or mysql.h for MYSQL -- you may have to install MYSQL in your system and/or pass MYSQL_DIR or MYSQL_INCDIR to the luarocks command.

I can make sure my mysql is install at `/usr/local/Cellar/mysql/5.6.23/`

**Comment by grasses** [comment]
I can find `mysql.h` in `/usr/local/Cellar/mysql/5.6.23/include/mysql`
My mysql is ok.

**Comment by hishamhm** [comment]
For the include dir, use MYSQL_INCDIR instead.

```
luarocks install luasql-mysql MYSQL_INCDIR=/usr/local/Cellar/mysql/5.6.23/include/mysql
```

**Comment by grasses** [comment]
It`s ok now. 
Thank you!!
