### ISSUE TITLE
LuaSQL ODBC

### ISSUE THREAD

**Issue by beauregardmark** [keplerproject/luasql#35]
The Luasql-odbc connection aborts when MS SQL columns with data types ntext, nchar, or nvarchar are selected.   Not sure if this is correctable in the ODBC driver.    Normal ANSI ASCII char and Extended ASCII character work fine text, char, and varchar data types in the existing driver.  However, need to use ntext, nchar, or nvarchar for Unicocde (UTF-8) characters.   Is there a solution for this?

**Comment by blumf** [comment]
Rolling this into #36
