### ISSUE TITLE
tests/odbc.lua - typo in variable name

### ISSUE THREAD

**Issue by jk77** [keplerproject/luasql#37]
Hello LuaSQL team,

Thanks for providing this LuaSQL interface.  Keep up the good work!

Found a typo is tests/odbc.lua that causes the "drop table" test in test.lua to report a failure when testing with an SQL Server database, even though the table was dropped successfully.

On line 30 of odbc.lua, variable DROP_TABLE_RETURN_VALUE0 should be renamed to DROP_TABLE_RETURN_VALUE (drop the 0) to fix.

Can create a pull request if needed.

Regards
jk77

**Comment by hishamhm** [comment]
> Can create a pull request if needed.

A PR is most welcome! Thanks!

**Comment by mpeterv** [comment]
(Fixed in #39)
