### ISSUE TITLE
env_connect postgres libpq memory leak

### ISSUE THREAD

**Issue by seanpringle** [keplerproject/luasql#45]
Before I go down this rabbit hole, a quick question in case I'm missing something obvious:

Ubuntu 14.04 LTS
lua-sql-postgres:amd64 2.3.0-3

Am seeing a memory leak when luasql fails to connect to Postgres. Memory footprint increases steadily for a long-running script with persistent connections that periodically attempts to reconnect to a database that is temporarily offline.

Is it intentional that ls_postgres.c `env_connect()` does not call `PQfinish()` when `PQstatus()` returns `CONNECTION_BAD`? At first glance it looks like a failed `PGconn` struct will never be seen by `conn_gc()`.

According to libpq docs [1] `PQfinish()` should be called even when a `PQstatus()` returns `CONNECTION_BAD` in order to release any memory allocated by libpq during the connection attempt. 

[1] http://www.postgresql.org/docs/9.5/static/libpq-connect.html#LIBPQ-PQFINISH

**Comment by tomasguisasola** [comment]
Thanks for pointing out the problem.  I think it is corrected now.  Could you, please, check the new version 2.3.2?

**Comment by seanpringle** [comment]
Thanks. 2.3.2 fixes the memory leak, but also causes #45.

**Comment by tomasguisasola** [comment]
Sure, my bad.  I hope the problem is now corrected.

Thanks,
Tomás
