### ISSUE TITLE
About LuaSQL.ODBC.pull28

### ISSUE THREAD

**Issue by jhernancanom** [keplerproject/luasql#51]
Hello, friends.

This message is for the team in charge of LuaSQL, specifically ODBC connection.

In January-2015 I put a request; I remember that it was numered with 27.

And you put a request numbered 28, that is in the TXT that I send join to this message.
LuaSQL.ODBC.url_**pull28**.txt

It referes to using an string connection instead a DSN.

In the pull 28 you states that the modification was done. I have the sources of the change.

But I see today that it is no in the **2016-06-22** download.

I would want to know what happend with this: Is it not posible to apply the adjusment? Is it not possible to use a string-connection instead a DSN? Is DSN the only way to ODBC-connect from Lua because a string-connection is not possible?

Thanks, friends.

**HERNAN CANO M**
Systems Analyst - Programmer

[LuaSQL.ODBC.url_pull28.txt](https://github.com/keplerproject/luasql/files/342301/LuaSQL.ODBC.url_pull28.txt)

**Comment by blumf** [comment]
#28 is quiet a big change. I haven't pulled it myself because I'd wanted others to review it first.

My personal [LuaSQL branch](/blumf/luasql) has the source for that and other extended feature on ODBC and Firebird, but needs work for the other drivers.

However, your other tickets, #50 and #52, suggest you have some bigger problems.

**Comment by jhernancanom** [comment]
Thank you, friend.

My supossing was correct: it is ver difficult to implment it. I must wait.

I'll go on with this info.



2016-07-01 8:20 GMT-05:00 blumf:

**Comment by jhernancanom** [comment]
((sorry, bugs with keyboard))

My supossing was correct: it is ver*y* difficult to impl*e*ment it. I must
wait.

2016-07-01 12:55 GMT-05:00 Hernan Cano:

> Thank you, friend.
>
> My supossing was correct: it is ver difficult to implment it. I must wait.
>
> I'll go on with this info.
>
>

**Comment by moteus** [comment]
There also avaliable [Lua-ODBC](https://github.com/moteus/lua-odbc) library wich provice almost full ODBC v3 API.

**Comment by jhernancanom** [comment]
Fine, Alexey.
Thanks.
I need to deep in LuaODBC.... I cannot see yet how it receives what is the
Provider (Firebird/InterBase(r) driver, PostgreSQL ANSI, SQL Server, SQLite
ODBC Driver, Microsoft Access Driver (*.mdb), etc...)

Normally in GitHub there is obly C-sources. Where can I get the .DLLs (I
use Lua v5.3)? Or where is there instructions for (a good) complete?


2016-07-25 4:45 GMT-05:00 Alexey Melnichuk:

> There also avaliable Lua-ODBC <https://github.com/moteus/lua-odbc>
> library wich provice almost full ODBC v3 API.
>
> —
>

**Comment by moteus** [comment]
To print all installed drivers just use
```Lua
odbc = require"odbc"
env=odbc.environment()
env:drivers(print)
```
https://github.com/moteus/lua-odbc/blob/22eb545f05ec94b98ac714f08616629a7c508ed9/.travis.yml#L51

To build on windows you can use msvc solution
https://github.com/moteus/lua-odbc/tree/master/msvc
But luarocks also works.

PS there also exists luasql compatiable module `odbc.luasql`

**Comment by jhernancanom** [comment]
Very fine, Alexey.

I will check this info and will talk about it to you.... by these means.


2016-07-25 13:07 GMT-05:00 Alexey Melnichuk:

**Comment by tomasguisasola** [comment]
Since there are no more messages, I think the issue was solved.
