### ISSUE TITLE
LuaSQL with MariaDB

### ISSUE THREAD

**Issue by Obi8** [keplerproject/luasql#64]
Can i use luasql with mariadb?

**Comment by tomasguisasola** [comment]
To use LuaSQL you have to choose a driver and there is no driver for 
MariaDB.  But since it seems to be similar to MySQL (to which there IS a 
driver) is should not be difficult to create a driver for it.

Regards,
Tomás

**Comment by Obi8** [comment]
Thanks for the information.

**Comment by ntd** [comment]
> ...there is no driver for MariaDB.

MariaDB is not a different database, it is a fork and drop-in replacement of MySQL, developed by the original maintainer of MySQL. As such it must works out of the box.

Depending on your distro you may need to install additional dependencies. In Archlinux you just need to install `libmariadbclient` while on Debian you need either `libmariadb-client-lgpl-dev` and `libmariadb-client-lgpl-dev-compat`.

**Comment by tomasguisasola** [comment]
Is that problem solved?
