### ISSUE TITLE
The Homepage is Out-of-Date

### ISSUE THREAD

**Issue by shlomif** [keplerproject/luasql#7]
http://www.keplerproject.org/luasql/ mentions only luasql-2.2.0 but there's already 2.4.0. It also appears the README on the Github repository root mentions an old version as well.

**Comment by tomasguisasola** [comment]
The correct homepage now is:

http://keplerproject.github.io/luasql/

**Comment by shlomif** [comment]
@tomasguisasola : thanks for the information.
