### ISSUE TITLE
libmysqlclient.so.18: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by aldus2** [keplerproject/luasql#76]
I updated some packages and since then, when using luasql, I have the execution error "libmysqlclient.so.18: cannot open shared object file: No such file or directory".
Looking for "libmysqlclient.so.18" on my disk, I only found "libmysqlclient.so.20".

This could be the reason of the error ?

**Comment by tomasguisasola** [comment]
Hi aldus2

LuaSQL drivers always depend on a binary library provided by the 
database.  If you remove that library, the driver won't work anymore.  
This seems to be your problem.

You can install the previous version of the database client library or 
recompile LuaSQL with the new one.  If you are using LuaRocks, you could 
remove the LuaSQL driver already installed and install it again.  This 
operation should try to recompile the driver (which is a .so file).  Try 
it and let me know if it solves your problem.

Regards,
Tomás

**Comment by aldus2** [comment]
Hi Tomás,

I (re)installed mysql client stuff. I entered 
`sudo luarocks install luasql-mysql MYSQL_INCDIR=/usr/include/mysql`
I got an error :
`Installing https://rocks.moonscript.org/luasql-mysql-2.3.5-1.rockspec...
Using https://rocks.moonscript.org/luasql-mysql-2.3.5-1.rockspec... switching to 'build' mode
sh: 1: git: not found

Error: LuaRocks 2.2.0 bug (please report at luarocks-developers@lists.sourceforge.net).
/usr/share/lua/5.1/luarocks/fetch/git.lua:19: attempt to index local 'version_string' (a nil value)
stack traceback:
/usr/share/lua/5.1/luarocks/fetch/git.lua:19: in function 'git_can_clone_by_tag'
/usr/share/lua/5.1/luarocks/fetch/git.lua:63: in function </usr/share/lua/5.1/luarocks/fetch/git.lua:33>
(tail call): ?
/usr/share/lua/5.1/luarocks/build.lua:197: in function </usr/share/lua/5.1/luarocks/build.lua:162>
(tail call): ?
/usr/share/lua/5.1/luarocks/build.lua:398: in function </usr/share/lua/5.1/luarocks/build.lua:386>
(tail call): ?
(tail call): ?
(tail call): ?
[C]: in function 'xpcall'
/usr/share/lua/5.1/luarocks/command_line.lua:208: in function 'run_command'
/usr/bin/luarocks:33: in main chunk
[C]: ?
`
As indicated, I filed the bug to luarocks-developers@lists.sourceforge.net with no answer yet.

To be continued.

**Comment by aldus2** [comment]
Hi !

I checked to install Mysql client (and even more libs that could be related, including Mysql-dev, including MariaDB client).
To check, I looked for libmysql on my hard drive : I checked that I have a fresh libmysqlclient.so.20.3.6 in /usr/lib/x86_64-linux-gnu, and libmysqlclient.so and libmysqlclient.so.20 (in that same folder) which are links to the former file, but no trace of libmysqlclient.so.18.
Is it possible to have libmysqlclient.so.20 without having libmysqlclient.so.18 ?

Regards,
Al

**Comment by tomasguisasola** [comment]
Hi Al

Yes it seems reasonable to have a newer version and not have an older 
one.  But did you succeded in compiling the driver for this new version?

Regards,
Tomás

**Comment by aldus2** [comment]
Hi Tomás,

Not yet because I am blocked by the luarocks bug and didn't succeed in passing the bug to the luarocks-developers@lists.sourceforge.net. I am working on it.

Al.
