### ISSUE TITLE
Linux mysql.h

### ISSUE THREAD

**Issue by captain1242** [keplerproject/luasql#77]
So while trying to install luasql for mysql I get the error:
```
Error: Could not find header file for MYSQL
  No file mysql.h in /usr/local/include
  No file mysql.h in /usr/include
```
and Google isn't helping, Google responds to me just with ways on Windows or how to use MySQL in C++

So where and how do I get the missing files?

**Comment by tomasguisasola** [comment]
Hi

You are not providing enough information, so I have to ask many 
questions:

1. did you have MySQL development files installed on your system?

    1.1. if not, the you'll have to install it :-)

2. where are the header files?

    2.1. you'll have to provide the path of the header files to the 
compiler to let it make and build the dynamic library.

3. how are you trying to install the driver?

    3.1. if you are using LuaRocks, then you can add 
"MYSQL_INCDIR=/path/to/mysql/headers" in the command line

    3.2. if you are using the Makefile distributed with the source, then 
you'll have to edit the file config to point to the proper path of the 
header files.

Hope this helps you!

Regards,
Tomás

**Comment by captain1242** [comment]
I have an MySQL server installed

I don't know, I assume at the default path <.<

btw I use Linux Debian 9.1 Stretch, and if you mean the package https://packages.debian.org/jessie/libmysqlclient-dev
it has no installation canidate

**Comment by captain1242** [comment]
which package does it require?

**Comment by captain1242** [comment]
ok found it, but luarocks adds an /include to the path <.< best. software. ever.
