### ISSUE TITLE
Attempting to install LuaSQL MySQL results in "cl is not recognized as an internal or external command"

### ISSUE THREAD

**Issue by mccrafter1212** [keplerproject/luasql#86]
I've never heard of "cl" although clearly I don't have it. When attempting to install luasql-mysql I do:
`./luarocks install luasql-mysql MYSQL_DIR="C:/Program Files/MySQL/MySQL Server 5.7"`
I then get this:
![error](https://user-images.githubusercontent.com/11711172/34085322-d2ddc902-e35c-11e7-959b-1599fee5f79f.png)
Obviously there's an error there with "cl" not being recognized. So how can I fix this?

**Comment by kcousins** [comment]
`cl.exe` is Microsoft's C and C++ compiler. To get any further:

- if you don't have it installed, you need to download and install Visual Studio, or
- otherwise, you should investigate getting it correctly configured.

**Comment by mccrafter1212** [comment]
@kcousins Thanks for responding. I do have Visual Studio installed (2017 & 2015) so I'm not sure why I'm getting this issue... How can I correctly configure this?

**Comment by mccrafter1212** [comment]
Okay, so I seem to have actually fixed my issue although ran into a new one. I'll close this issue and post a new one.

**Fix to this issue:**
Use Developer Command Prompt for VS2015 (or other year / version) when running the installation command. You're going to need to do `cd ..` assuming your current path is `C:\Program Files (x86)\Microsoft Visual Studio` and then do `cd LuaRocks` to access the LuaRocks directory. Once there just run your installation command and everything *should* work fine.
