### ISSUE TITLE
Update Luarock

### ISSUE THREAD

**Issue by CodelessFuture** [keplerproject/luasql#92]
Can I ask you to update the luarockt for this project, please?

**Comment by mpeterv** [comment]
You probably shouldn't spam issues like this. In particular, luacov of all the keplerproject rocks does not require an update currently.

**Comment by mpeterv** [comment]
Wrong issue because I had 20 of them open...

**Comment by CodelessFuture** [comment]
You don't have 20 but only 7 or 8....apart from Luacov all the other I post an issue require update in luarocks, sorry if I write one more than necessary.

**Comment by CodelessFuture** [comment]
No need sorry. After more analysis needs to be updated only cgilua, wsapi and copxcall.
