### ISSUE TITLE
Looking LuaSQL

### ISSUE THREAD

**Issue by jhernancanom** [keplerproject/luasql#93]
Looking LuaSQL

Hi, friends.

I am trying to get info about LuaSQL, but the links seem broken.

In http://www.promixis.com/lua/luasql/index.html I found the following two:

LuaForge  
http://luaforge.net/project/showfiles.php?group_id=12

LuaBinaries 
http://luaforge.net/projects/luabinaries/

It seems that LuaForge got into GitHub  (( https://github.com/luaforge )), but I donot see LuaSQL there

In http://keplerproject.github.io/luasql/  I got redirected to an URL based in LuaRocks, but without the DLLs.

In " History - LuaSQL 2.3.5 [23/Feb/2017] " (( http://keplerproject.github.io/luasql/history.html )) says that:

Added some bug corrections and tested with Lua versions 5.1, 5.2 and 5.3 (only Postgres, MySQL and SQLite were tested by the time of the launch).

I want to test with FireBird and SQLite3.

The forum Kepler developers, called "Kepler's mailing list" is not active, this was what Fabio says me.

Can you say me where can I find the LuaSQL DLLs, avoiding LuaRocks or with instructions that runs without this?

Moteus: Is odbc.luasql different from luasql.odbc? Can you say me where can I find it?

Thanks.

**Comment by jhernancanom** [comment]
Thanks, Thomas.

>>> Sorry, but I cannot test FireBird, but SQLite3 was tested. I can send
you
>>>  an blindly updated file for you to test it. Bu you'll need to biuld the
>>>  DLL and put it in the correct place to allow Lua to find it when
>>>  require'ing it.

I can test with FireBird.
Send me what you say.
I can build the DLL if you say me instructions for this.

>>> I use only Linux, thus I cannot build DLLs. Have you tried to compile
the
>>> drivers by yourself?

No, because I do not have instructions for that.

See you later.

**Comment by tomasguisasola** [comment]
Hi

Can you understand the Makefile and translate it to whatever compiler
you're using?

Regards,
Tomás

Em qua, 8 de ago de 2018 às 03:28, jhernancanom <notifications@github.com>
escreveu:
